### ISSUE TITLE
Gaya Penulisan Kode

### ISSUE THREAD

**Issue by jefrydco** [rudestewing/himit-pens-cari-teks#1]
Hi Mas Rudi, terima kasih sudah mengirimkan kode belajar Vue.js Fundamental, saya sangat mengapresiasi kerja keras Mas Rudi.

Mas juga sudah menggunakan Vue CLI dan Tailwind CSS untuk aplikasi pencari teks video YouTube ini. Luar biasa Mas!

Saya punya 1 saran kecil terkait gaya penulisan kode Mas. Pada berkas `src/App.vue` baris ke 9 berikut:

https://github.com/rudestewing/himit-pens-cari-teks/blob/021e91f1ab28ec8d17175b06bfa6925c7d43db7d/src/App.vue#L9

menurut saya akan lebih baik ada spasi di antara kedua simbol kurung kurawal ganda. Kurang lebih hasilnya nanti akan seperti berikut:

```html
Source Video URL [{{ videoUrl }}]
```

Semua contoh kode pada dokumentasi resmi Vue.js juga demikian cara penulisannya. Lebih lengkap mengenai gaya penulisan Vue.js Mas dapat membaca pada tautan berikut, [Dokumentasi Vue.js Bahasa Indonesia - Panduan Gaya](https://docs.vuejs.id/v2/style-guide)

Semangat Mas! 😄

**Comment by rudestewing** [comment]
Hai mas Jefry

makasih banyak mas sudah repot repot email ke saya
saya seneng banget jujur.



makasih mas !!!

baru ini saya dapet review begini

dari sekian banyak peserta yang ada sekitar 200an itu punya saya dapet
review


makasih banyak mas sekali lagi

baik terima kasih masukannya mas
masalah penulisan akan saya perbaiki


saya juga ingin menambah kenalan dan koneksi mungkin kedepannya apakah kita
bisa sharing-sharing lagi ?


Salam
Rudi Setiawan

**Comment by jefrydco** [comment]
Hi Mas @rudestewing , terima kasih kembali Mas. Sebenarnya saya kirim ulasannya bukan melalui email Mas tetapi melalui Isu GitHub. Mas bisa melihat isunya melalui tautan berikut https://github.com/rudestewing/himit-pens-cari-teks/issues/1 . Nanti kalau Mas sudah ada waktu dan berkenan untuk memperbaiki kodenya, Mas bisa menutup isunya.

> saya juga ingin menambah kenalan dan koneksi mungkin kedepannya apakah kita bisa sharing-sharing lagi ?

Boleh banget Mas, kalau mau diskusi langsung kontak ajah Mas gapapa, semua sosial media saya identitasnya bernama jefrydco. 😄

**Comment by rudestewing** [comment]
Oh iya mas saya barusan cek ternyata itu issue di github

saking senengnya dapet email hahahah

okeh mas sip thanks ya

**Comment by rudestewing** [comment]
sudah di fix
